version: '3.8'
services:
  database:
    image: mysql
    container_name: service_database
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ADM}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      - market-place

  api:
    image: ${APPLICATION_DOCKER_IMAGE}
    container_name: application-market-place
    ports:
      - "${APPLICATION_PORT}:8080"
    restart: on-failure
    depends_on:
      - database
    networks:
      - market-place
    environment:
      - DATABASE_SERVER_URL=${DATABASE_SERVER_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

volumes:
  database:

networks:
  market-place:
    driver: bridge